(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb roomc ball4 ball3 ball2 ball1 left right)
   (:init (rooma)
          (room roomb)
          (room roomc)
          (connected roomb rooma)
           (connected rooma roomb)
           (connected roomc roomb)
           (connected roomb roomc)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (free right)
          (free2 left)
          (free2 right)
          (at ball4 rooma)
          (at ball3 rooma)
          (at ball2 rooma)
          (at ball1 rooma)
          (gripper left)
          (gripper right))
   (:goal (and (at ball4 roomb)
               (at ball3 roomc)
               (at ball2 roomb)
               (at ball1 roomb))))