(define (problem gripper-problem)
    (:domain gripper-continuous)

    (:objects
        mover1 mover2 - mover
        ball1 ball2 ball3 ball4 ball5 ball6 ball7 ball8 ball9 - ball
        loader1 loader2 - loader
        A B C - group
    )

    (:init
        (mover mover1)
        (mover mover2)
        (free mover1)
        (free mover2)
        (equal mover1 mover1)
        (equal mover2 mover2)
        (= (at-robby mover1) 0)  
        (= (at-robby mover2) 0)  
        (not (moving mover1))
        (not (moving mover2))
        (= (battery mover1) 20)
        (= (battery mover2) 20)
        (= (maxbattery) 200)
        
        (= (max_vel mover1) 10)
        (= (max_vel mover2) 10)
        
        (= (velocity mover1) 10)
        (= (velocity mover2) 10)
        
        ; (= (batterytimer) 0)
        
        (ball ball1)
        (ball ball2)
        (ball ball3)
        (ball ball4)
        (ball ball5)
        (ball ball6)
        (ball ball7)
        (ball ball8)
        (ball ball9)
        (not (isloaded ball1))
        (not (isloaded ball2))
        (not (isloaded ball3))
        (not (isloaded ball4))
        (not (isloaded ball5))
        (not (isloaded ball6))
        (not (isloaded ball7))
        (not (isloaded ball8))
        (not (isloaded ball9))
        (= (position ball1) 10)
        (= (position ball2) 20)
        (= (position ball3) 30)
        (= (position ball4) 50)
        (= (position ball5) 60)
        (= (position ball6) 70)
        (= (position ball7) 80)
        (= (position ball8) 90)
        (= (position ball9) 100)
        (= (weight ball1) 7)
        (= (weight ball2) 3)
        (= (weight ball3) 2)
        (= (weight ball4) 6)
        (= (weight ball5) 70)
        (= (weight ball6) 2)
        (= (weight ball7) 60)
        (= (weight ball8) 7)
        (= (weight ball9) 70)
        (not (isfragile ball1))
        (not (isfragile ball2))
        (not (isfragile ball3))
        (not (isfragile ball4))
        (not (isfragile ball5))
        (not (isfragile ball6))
        (not (isfragile ball7))
        (not (isfragile ball8))
        (not (isfragile ball9))
        (= (belong ball1) 3)
        (= (belong ball2) 3)
        (= (belong ball3) 2)
        (= (belong ball4) 2)
        (= (belong ball5) 2)
        (= (belong ball6) 0)
        (= (belong ball7) 1)
        (= (belong ball8) 0)
        (= (belong ball9) 1)
        (= (x) 100)
        (group A)
        (group B)
        (group C)
        (= (numofgroup A) 1)
        (= (numofgroup B) 2)
        (= (numofgroup C) 3)
        (= (elementspergroup A) 2)
        (= (elementspergroup B) 3)
        (= (elementspergroup C) 2)

        (= (currentgroup) 0)

        (loader loader1)
        (= (loadertimer loader1) 0)
        (not (busyloading loader1)) 
        (loader loader2)
        (= (loadertimer loader2) 0)
        (not (busyloading loader2)) 
        (not (ischeap loader2))
        (not (ischeap loader1))

        (not (currentgroupset))
    )

    (:goal
        (and 
            (isloaded ball1)
            (isloaded ball2)
            (isloaded ball3)
            (isloaded ball4)
            (isloaded ball5)
            (isloaded ball6)
            (isloaded ball7)
            (isloaded ball8)
            (isloaded ball9)
        )
    )

)
