(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb roomc crate4 crate3 crate2 crate1 left right)
   (:init (rooma)
          (room roomb)
          (room roomc)
          (connected roomb rooma)
           (connected rooma roomb)
           (connected roomc roomb)
           (connected roomb roomc)
          (crate crate4)
          (crate crate3)
          (crate crate2)
          (crate crate1)
          (rob_position rooma)
          (free left)
          (free right)
          (free2 left)
          (free2 right)
          (at crate4 rooma)
          (at crate3 rooma)
          (at crate2 rooma)
          (at crate1 rooma)
          (gripper left)
          (gripper right))
   (:goal (and (at crate4 roomb)
               (at crate3 roomc)
               (at crate2 roomb)
               (at crate1 roomb))))